version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ayora_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/ayora_dev
      AI_SERVICE_URL: http://ai-stub:8000/analyze
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
      ai-stub:
        condition: service_started
    volumes:
      - .:/app
      - /app/node_modules

  ai-stub:
    build: ./ai-stub
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development

volumes:
  postgres_data:
